// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu26tJ0wQ71HY3gnqCr1kj4SnSom5Lp20',
    appId: '1:333151990063:web:b63f6e15f09f9916d371da',
    messagingSenderId: '333151990063',
    projectId: 'doktory-89318',
    authDomain: 'doktory-89318.firebaseapp.com',
    storageBucket: 'doktory-89318.firebasestorage.app',
    measurementId: 'G-SB6TYZQWCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eiWzLcati5kXfDM_CRQiT__QhouDpC0',
    appId: '1:333151990063:android:14c9ea172145d6b8d371da',
    messagingSenderId: '333151990063',
    projectId: 'doktory-89318',
    storageBucket: 'doktory-89318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARuzZi7upQcKsTPtm90RrWwVZlCW-Z5RE',
    appId: '1:333151990063:ios:1b67c9272e3ebf3ed371da',
    messagingSenderId: '333151990063',
    projectId: 'doktory-89318',
    storageBucket: 'doktory-89318.firebasestorage.app',
    iosBundleId: 'com.example.doktory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARuzZi7upQcKsTPtm90RrWwVZlCW-Z5RE',
    appId: '1:333151990063:ios:1b67c9272e3ebf3ed371da',
    messagingSenderId: '333151990063',
    projectId: 'doktory-89318',
    storageBucket: 'doktory-89318.firebasestorage.app',
    iosBundleId: 'com.example.doktory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu26tJ0wQ71HY3gnqCr1kj4SnSom5Lp20',
    appId: '1:333151990063:web:ef2424b0881d7c77d371da',
    messagingSenderId: '333151990063',
    projectId: 'doktory-89318',
    authDomain: 'doktory-89318.firebaseapp.com',
    storageBucket: 'doktory-89318.firebasestorage.app',
    measurementId: 'G-JB6E6WLH4H',
  );

}